name: Release
on:
  push:
    branches:
      - master
env:
  PROTOBUF_SHA: 655310ca192a6e3a050e0ca0b7084a2968072260
jobs:
  rust-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            artifact: bazel-runner-macos
          - os: ubuntu-latest
            artifact: bazel-runner-linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Prepare outputs from platform run
        run: ./.github/ci_scripts/prepare_output.sh ${{ matrix.artifact }} staging-directory
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.artifact }}
          path: staging-directory
  make_release:
    name: Make release
    needs: rust-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download linux bazel-runner
        uses: actions/download-artifact@v1
        with:
          name: bazel-runner-linux
          path: downloads
      - name: Download macos bazel-runner
        uses: actions/download-artifact@v1
        with:
          name: bazel-runner-macos
          path: downloads
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.1-${{ github.run_number }}"
          prerelease: false
          title: "Auto generated release for protobuf: ${{ env.PROTOBUF_SHA }}"
          files: |
            downloads/bazel-runner-macos
            downloads/bazel-runner-macos.sha256
            downloads/bazel-runner-linux
            downloads/bazel-runner-linux.sha256
        id: "automatic_releases"
